http.o: http.c headers/http.h headers/url.h
main.o: main.c headers/socket.h headers/http.h headers/url.h \
 headers/url.h headers/mime.h headers/stats.h headers/http.h
mime.o: mime.c headers/mime.h
socket.o: socket.c headers/socket.h
stats.o: stats.c headers/stats.h headers/http.h headers/url.h
url.o: url.c headers/url.h
